[package]
name = "murmur"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
core-graphics = "0.25.0"
cpal = "0.18.2"
eframe = "0.36.2"
encoding_rs = "0.8.35"
enigo = "0.6.1"
handy-keys = "0.3.4"
hf-hub = "1.0.0"
indicatif = "0.18"
llama-cpp-2 = "0.1.156"
samplerate = "0.2.4"
sherpa-onnx = "1.13.8"
tokio = { version = "1.53.1", features = ["full"] }
tray-icon = { version = "0.25.1", default-features = false }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
