[package]
name = "test-egggg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
core-graphics = "0.25.0"
cpal = "0.18.2"
eframe = "0.36.2"
enigo = "0.6.1"
handy-keys = "0.3.4"
hf-hub = "1.0.0"
mistralrs = {version = "0.8.1", features = ["metal"] }
sherpa-onnx = "1.13.8"
tokio = { version = "1.53.1", features = ["full"] }
tray-icon = { version = "0.25.1", default-features = false }

[patch.crates-io]
mistralrs-core = { path = "third_party/mistral.rs/mistralrs-core" }
